### ISSUE TITLE
custom start at line number

### ISSUE THREAD

**Issue by nirgn975** [atomiks/rehype-pretty-code#44]
I'm looking for a way to start the line numbers from a specific number (every code block will be different, based to the code section I'm showing from the whole file).

I managed to set it up manually using:
```css
code[data-line-numbers] > .line:first-of-type::before {
  counter-set: line 100;
}
```
or
```css
counter-reset: line 100;
```
So the numbers start at 100.

But I didn't find a way to set the number (100) from the markdown code block itself.
Or maybe even put it in a custom attribute so I can get it in the css like this: `attr(data-start-at)`.
Am I missing something?
